import sapien.core as sapien
import mplib
from mplib import Pose
import cv2
class MotionPlanning:
    def __init__(self,robot_config,controller):
        self.setup_planner(urdf_path=robot_config['urdf_path'],srdf_path=robot_config['srdf_path'],move_group=robot_config['hand_name'])
        self.controller = controller
    
    def setup_planner(self, **kwargs):
        """
        Create an mplib planner using the default robot.
        See planner.py for more details on the arguments.
        """
        self.planner = mplib.Planner(
            urdf=kwargs.get("urdf_path", "./data/panda/panda.urdf"),
            srdf=kwargs.get("srdf_path", "./data/panda/panda.srdf"),
            move_group=kwargs.get("move_group", "right_hand"),
        )

    # follow path ankor
    def follow_path(self, result):
        """Helper function to follow a path generated by the planner"""
        # number of waypoints in the path
        n_step = result["position"].shape[0]
        # this makes sure the robot stays neutrally boyant instead of sagging
        # under gravity
        for i in range(n_step):
            qf = self.controller.robot.compute_passive_force(
                gravity=True, coriolis_and_centrifugal=True
            )
            self.controller.robot.set_qf(qf)
            # set the joint positions and velocities for move group joints only.
            # The others are not the responsibility of the planner
            for j in range(len(self.planner.move_group_joint_indices)):
                self.controller.robot.active_joints[j].set_drive_target(result["position"][i][j])
                self.controller.robot.active_joints[j].set_drive_velocity_target(
                    result["velocity"][i][j]
                )
            # simulation step
            self.controller.scene.step()
            # render every 4 simulation steps to make it faster
            if i % 4 == 0:
                self.controller.scene.update_render()
                self.controller.viewer.render()
                self.controller.camera.take_picture()
                rgb = self.controller.camera.get_picture("Color") 
                rgb = (rgb * 255).clip(0, 255).astype("uint8")
                # rgb = self.controller.camera.get_rgb()
                bgr = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)
                self.controller.out.write(bgr)
    # follow path ankor end
    def set_gripper(self, pos):
        """
        Helper function to activate gripper joints
        Args:
            pos: position of the gripper joint in real number
        """
        # The following two lines are particular to the panda robot
        for joint in self.controller.robot.active_joints[-2:]:
            joint.set_drive_target(pos)
        # 100 steps is plenty to reach the target position
        for i in range(100):
            qf = self.controller.robot.compute_passive_force(
                gravity=True, coriolis_and_centrifugal=True
            )
            self.controller.robot.set_qf(qf)
            self.controller.scene.step()
            if i % 4 == 0:
                self.controller.scene.update_render()
                self.controller.viewer.render()
                            
    def open_gripper(self):
        self.set_gripper(0.4)

    def close_gripper(self):
        self.set_gripper(0)
                     
    def move_to_pose_with_RRTConnect(self, pose: Pose):
        """
        Plan and follow a path to a pose using RRTConnect

        Args:
            pose: mplib.Pose
        """
        # result is a dictionary with keys 'status', 'time', 'position', 'velocity',
        # 'acceleration', 'duration'
        # plan_pose ankor
        print("plan_pose")
        result = self.planner.plan_pose(pose, self.controller.robot.get_qpos(), time_step=1 / 250)
        # plan_pose ankor end
        if result["status"] != "Success":
            print(result["status"])
            return -1
        # do nothing if the planning fails; follow the path if the planning succeeds
        self.follow_path(result)
        return 0
                  
    def move_to_pose_with_screw(self, pose):
        """
        Interpolative planning with screw motion.
        Will not avoid collision and will fail if the path contains collision.
        """
        result = self.planner.plan_screw(
            pose,
            self.controller.robot.get_qpos(),
            time_step=1 / 250,
        )
        if result["status"] == "Success":
            self.follow_path(result)
            return 0
        else:
            # fall back to RRTConnect if the screw motion fails (say contains collision)
            return self.move_to_pose_with_RRTConnect(pose)
                       
    def move_to_pose(self, pose, with_screw=True):
        """API to multiplex between the two planning methods"""
        if with_screw:
            return self.move_to_pose_with_screw(pose)
        else:
            return self.move_to_pose_with_RRTConnect(pose)